import React, { ReactNode } from 'react';
import type { Metadata } from 'next';

// These styles apply to every route in the application
import { Jost } from "next/font/google";
import 'tailwindcss/tailwind.css';
import "./globals.css";
import './main.js';
// import RootLayout from './page';
import "./styles/icons.css";
import 'bootstrap/dist/css/bootstrap.min.css';

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import Hero from './Components/Hero';
config.autoAddCss = false;

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const jost = Jost({ subsets: ["latin"] });

interface LayoutProps {
  children: ReactNode;
}

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   )
// }

const RootLayout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <html>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" ></link>
        <link href="https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet"></link>
      </head>
      <body className={jost.className}>
        <main>
          {/* Render the children components */}
          {children}

        </main>
      </body>
    </html>



  );
};

export default RootLayout;

